### ISSUE TITLE
Feature Request: Add 'state' variable similar to 'level'

### ISSUE THREAD

**Issue by cpinkham** [toddaustin07/HTTPDevices#1]
Would it be possible to add a ${state} variable for switches and dimmers similar to ${level} to allow a single URL to be used for both on and off and have the desired state passed as an argument?  This could initially be added to the existing on/off URLs, but it would make setup simpler if the user only had to provide a single URL if the URL included the ${state} variable.

**Comment by toddaustin07** [comment]
Yes, that could be done.  I have a few things due to be updated in this driver, so I'll take a look at including this in the next release.

**Comment by cpinkham** [comment]
Thanks, and great work on this and webrequestor.  If we could also pass in the label of the virtual entity using {label}, or possibly even better, the Smartthings Device Network ID then we could potentially use the same URL for all virtual switches and possibly other types as well.  Maybe a {type} variable as well could be passed.

I have a pair of PHP helper scripts that I am using in conjunction with Home Assistant and HTTPDevices.  One helper is for ST -> HA and the other is for HA -> ST.  Once I refine them a little more and maybe collapse the two and write some notes, I might post to my github.  The HA helper is called via a HA automation that triggers whenever one of my lights changes state and it uses the ST REST API to update the state of the virtual switch in ST.  Right now, my HA -> ST helper has a map of HA entity IDs to ST deviceIDs but this could be queried on the fly via the API.  The URLs I am using with HTTPDevices contain a hardcoded HA entity_id, but if we were able to have a variable for the ST Device Network ID, the HA entity_id could be put there and the same URL could be used for all virtual switches.

**Comment by toddaustin07** [comment]
Please see this notice of driver update on the community boards:
https://community.smartthings.com/t/st-edge-web-requestor-a-driver-to-issue-local-post-and-get-http-requests/232911/518?u=taustin

I think this should address your feature request.  Please confirm so we can close the issue.  Thanks.

**Comment by cpinkham** [comment]
This change worked great, I now use one URL per virtual switch instead of two.  Now if only we could have the SmartThings "Device Network Id" passed in on the URL, we could use a single URL for all devices.  Closing this ticket since the original request has been implemented.  Thanks.
